### PR TITLE
Massive upgrade and refactor

### PR DESCRIPTION
**Pull request by vadixidav**
This PR does the following:

- Upgrade dependencies.
- Add documentation for almost everything.
- Refactor `&'static str` errors into `FlannError` using the `failure` crate.
- Appease all clippy lints.
- Change `flann-sys` to use `CMake` to build a consistent FLANN version from a git submodule.
  - Git submodule will allow offline builds as well since it will get packaged with the crate source.
- Update to FLANN `1.9.1` native C bindings.
- Remove wrapper build.
- Rename some methods to improve clarity.
- Add `SliceIndex` which forces all slices from the consumer to outlive the index.
- Use `assert_approx_equals` in tests on floating point types.
- Fully flesh out checks in some tests.
- Add appropriate trait bounds on inputs and return iterators where appropriate.
- Remove `rebuild_threshold` from arguments and add it to `Parameters`.

Let me know if you want to also support linking to the system FLANN installation. I don't like depending on `CMake` during a `cargo build`, but there are other crates that do the same thing.

### CODE REVIEW

**Comment by vadixidav** [comment]
I have only tested this on Windows currently, but since it uses CMake and C types where possible, my hope is that it will build fine on Linux. Tomorrow morning I will test it on Linux and fix any remaining issues.

**Comment by vadixidav** [comment]
The build and tests are now working on `Ubuntu 18.04.2` for me.

**Comment by adnanademovic** [comment]
Hi Geordon,

I'm currently not using this for anything, and am very busy, so I don't think I'm currently right for the sole maintainer job.

I'm giving you owner rights so you have the flexibility to extend the library as you please. It's better than it rotting and becoming obsolete under my rule.

**Comment by vadixidav** [comment]
@adnanademovic Sure, I can take over it. I am working more with binary descriptors currently in photogrammetry applications, but I want the option to work with floating point features too. I am also interested in using this for machine learning as well. For binary descriptors I may need to see if I can enable LSH with the current parameter set and how to do that, then I might make special bindings for bit vectors (sort of like how there are `Vec` and `GenericArray` bindings now). I can set up Travis CI for the repository as well.

**Pull request merged**
